const mongoose = require("mongoose");

const loanSchema = new mongoose.Schema(
    {
        // Automatically generated by the system
        entryNumber: {
            type: Number,
            unique: true,
            sparse: true
        },

        // Manually entered by the user
        allotmentNumber: {
            type: String,
            default: "",
            trim: true
        },

        // Automatically generated by the system
        loanId: {
            type: String,
            unique: true,
            required: true
        },

        client: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Client",
            required: true
        },

        location: {
            type: String,
            required: true,
            trim: true
        },

        metalType: {
            type: String,
            enum: ["Gold", "Silver"],
            required: true
        },

        itemDescription: {
            type: String,
            required: true,
            trim: true
        },

        grossWeight: {
            type: Number,
            required: true,
            min: 0
        },

        netWeight: {
            type: Number,
            required: true,
            min: 0
        },

        principalAmount: {
            type: Number,
            required: true,
            min: 0
        },

        interestRate: {
            type: Number,
            required: true,
            min: 0
        },

        loanDate: {
            type: Date,
            required: true
        },

        returnDate: {
            type: Date,
            default: null
        },

        applicableDays: {
            type: Number,
            default: null
        },

        interestAmount: {
            type: Number,
            default: 0
        },

        finalAmount: {
            type: Number,
            default: 0
        },

        status: {
            type: String,
            enum: [
                "Active",
                "Closed",
                "Overdue"
            ],
            default: "Active"
        },

        notes: {
            type: String,
            trim: true
        },

        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        },

        updatedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        }
    },
    {
        timestamps: true
    }
);

module.exports =
    mongoose.model(
        "Loan",
        loanSchema
    );
    